"""Initial migrattion

Revision ID: d84fe03d37b6
Revises: a6ea3d28183b
Create Date: 2023-04-27 20:58:08.319311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd84fe03d37b6'
down_revision = 'a6ea3d28183b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
